export const LOGIN_REQUEST = " LOGIN_REQUEST"

export const LOGIN_SUCCESS = " LOGIN_SUCCESS"

export const LOGIN_FAIL = " LOGIN_FAIL"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"

export const REGISTER_USER_FAIL = " REGISTER_USER_FAIL"

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST"

export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"

export const FORGET_PASSWORD_FAIL = " FORGET_PASSWORD_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
